### ISSUE TITLE
Accessing RAM with peek and poke

### ISSUE THREAD

**Issue by grue74** [mlund/ultimate64#1]
Hello, it seems that accessing RAM is not possible while using peek command.
Is it possible to have an additional parameter to define that RAM is preferred while doing peek?
Like when doing peek 0xe000 -n 256 I get kernal rom.

Also, I'd like to see also hex notation for values, currently peek 0xe000 -n 0x100 is sadly not possible. Same goes for poke command, you can currently only poke decimal values.

Memory fill option for poke? "poke 0x1000 00 -n 256" doesn't seem to be valid option.
Also, it would be must to be able to optionally poke into RAM instead of IO. Like "poke 0xd020 0" wouldn't change color, but instead goes into ram under IO area.

**Comment by mlund** [comment]
Thanks for the input! So three feature requests we can track in this issue:
- [x] Allow hex and binary input for values (#2)
- [x] a `fill` command (see #8)
- [ ] [Bank switching](https://www.c64-wiki.com/wiki/Bank_Switching). Currently this can be achieved with a preceding poke to memory address $1. This is an unsafe operation if e.g. an interrupt uses rom routines or tries to access hardware registers. We should probably pause/resume before attempting this. @grue74 can you detail your use case to guide the design?

# Update

Reading both address 0 and 1, the REST API seems to always return zero, while if using Basic PEEK we see the non-zero default values. The machine code monitor in the Ultimate web-interface also shows zero. Any ideas why this is?

**Comment by mlund** [comment]
Closing this for now as the REST API currently doesn't allow changing address 0 and 1. This is because it's using DMA and bypasses the CPU.
